[package]
name = "easing-function"
version = "0.1.0"
edition = "2021"
rust-version = "1.65.0"

[features]
serde = ["dep:serde"]

[dependencies]
serde = { version = "1.0.208", optional = true, features = ["derive"] }
